name: ิปีด ีกีผีกีปีซีถ Workflow-ีจ

on: push  # ิฑีตีฝีซีถึีถี ีกีดีฅีถ ีกีถีฃีกีด push-ีซ ีคีฅีบึีธึีด ีกีตีฝ ีฃีธึีฎีธีฒีธึีฉีตีธึีถีถีฅึีจ ีฏีกีทีญีกีฟีฅีถ

jobs:
  say-hello:
    runs-on: ubuntu-latest  # GitHub-ีจ ีฏีฝีฟีฅีฒีฎีซ ีชีกีดีกีถีกีฏีกีพีธึ Ubuntu ีฝีฅึีพีฅึ

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3  # ีีกีทีธึีด ีง ึีธ ีถีกีญีกีฃีฎีซ ึีกีตีฌีฅึีจ

      - name: Say Hello
        run: echo "ิฒีกึึ ึีฅีฆ GitHub Actions-ีซึ ๐"
